In [23]:
### Size of chess board
global N
N=8
import numpy as np

In [31]:
def IsSafe(x,y,sol):
    return (x>=0 and x<N and y>=0 and y<N and sol[x][y]==-1)
    

In [45]:
def solveKT():
    ### Initialize matrix
    sol=np.zeros((N,N), dtype=np.int)
    for x in range(0,N):
        for y in range(0,N):
            sol[x][y] = -1;
    xMove = [2,1,-1,-2,-2,-1, 1, 2]
    yMove = [1,2,2,1,-1,-2,-2, -1]
    sol[0][0]=0
    if (solveKTUtil(0, 0, 1, sol, xMove, yMove) == False):
    
        print("Solution does not exist")
        return False
    
    else:
        print(sol)
 
    return True

In [46]:
def solveKTUtil(x,y,movei,sol,xMove,yMove):
    if (movei == N*N):
        return True
 
    ##Try all next moves from the current coordinate x, y */
    for k in range(0,N):
        next_x = x + xMove[k]
        next_y = y + yMove[k]
        if (IsSafe(next_x, next_y, sol)):
            sol[next_x][next_y] = movei
            if (solveKTUtil(next_x, next_y, movei+1, sol,
                         xMove, yMove) == True):
                 return True
            else:
                sol[next_x][next_y] = -1
    
   
 
    return False


In [47]:
if __name__ == '__main__':
    solveKT()

[[ 0 59 38 33 30 17  8 63]
 [37 34 31 60  9 62 29 16]
 [58  1 36 39 32 27 18  7]
 [35 48 41 26 61 10 15 28]
 [42 57  2 49 40 23  6 19]
 [47 50 45 54 25 20 11 14]
 [56 43 52  3 22 13 24  5]
 [51 46 55 44 53  4 21 12]]
